#! /bin/bash

echo  " Atualizando o servidor... "
apt-get atualização
apt-get upgrade -y
apt-get install apache2 -y
apt-get install unzip -y


echo  " Baixando e copiando os arquivos da aplicação... "

cd /tmp
wget https://github.com/luamlima/linux-projeto/archive/refs/heads/main.zip
descompacte main.zip
cd linux-site-dio-main
cp -R * /var/www/html/
